name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  detectonly:
    name: Detect use of .only
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Detect use of .only
        run: |
          grep -rq --include '*.spec.js' \.only\( . && echo 'You have .only() in your tests!' && exit 1
          exit 0
  test_wtr:
    name: Test web components
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Chrome headless
        run: |
          yarn install
          yarn playwright install-deps
          yarn playwright install
          yarn test
  test_bos:
    name: Test BOS E2E
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Chrome headless
        run: |
          yarn install
          yarn playwright install-deps
          yarn playwright install
          yarn test_bos
