name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  detectonly:
    name: Detect use of .only
    runs-on: ubuntu-jammy
    steps:
      - uses: actions/checkout@v2
      - name: Detect use of .only
        run: |
          grep -rq --include '*.spec.js' \.only\( . && echo 'You have .only() in your tests!' && exit 1
          exit 0
  test_wtr:
    name: Test web components
    runs-on: ubuntu-jammy
    steps:
      - uses: actions/checkout@v2
      - name: Test web components
        run: |
          yarn install
          yarn playwright install-deps
          yarn playwright install
          yarn test
  test_bos:
    name: Test BOS E2E
    runs-on: ubuntu-jammy
    steps:
      - uses: actions/checkout@v2
      - name: Test BOS E2E
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/mpeterdev/bos-loader/releases/download/v0.11.0/bos-loader-v0.11.0-installer.sh | sh
          yarn install
          yarn playwright install-deps
          yarn playwright install
          yarn dist
          yarn test:e2e
